import { getSupabaseClient } from '../lib/supabase';
import { Lead } from '../types';

/**
 * SQL snippet to initialize the database correctly.
 */
export const INITIALIZATION_SQL = `
-- Create the leads table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT,
  role TEXT,
  newsletter_opt_in BOOLEAN DEFAULT FALSE
);

-- Enable RLS
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to insert leads (Public Submission)
CREATE POLICY "Allow public insert" ON leads 
FOR INSERT WITH CHECK (true);
`;

/**
 * Verifies the health of the connection and provides actionable feedback.
 */
export const testDatabaseConnection = async (manualKey?: string): Promise<{ success: boolean; message: string; code?: string; sql?: string }> => {
  const client = getSupabaseClient(manualKey);
  
  if (!client) {
    return { 
      success: false, 
      message: `The Supabase Publishable (anon) API Key is missing or invalid.`,
      code: 'KEY_MISSING'
    };
  }

  try {
    // Attempt to query the table to check existence and permissions
    const { error } = await client
      .from('leads')
      .select('id')
      .limit(1);

    if (error) {
      console.error("Supabase Diagnostic Error:", error);
      
      if (error.code === '42P01') {
        return { 
          success: false, 
          message: 'Table "leads" does not exist in your Supabase project.', 
          code: error.code,
          sql: INITIALIZATION_SQL
        };
      }
      if (error.code === '42501') {
        return { 
          success: false, 
          message: 'RLS Permission Denied. You need to add an "Insert" policy for the public.', 
          code: error.code,
          sql: 'CREATE POLICY "Allow public insert" ON leads FOR INSERT WITH CHECK (true);'
        };
      }
      if (error.code === 'PGRST301') {
        return {
          success: false,
          message: 'JWT Secret mismatch. Your API Key might be invalid or from a different project.',
          code: error.code
        };
      }
      return { success: false, message: `Supabase Error: ${error.message} (Code: ${error.code})`, code: error.code };
    }

    return { success: true, message: 'Connection Verified: Agentix Protocol is synchronized with your Supabase database.' };
  } catch (err: any) {
    return { success: false, message: `Network Error: ${err.message || 'Check your internet connection or Supabase URL'}` };
  }
};

/**
 * Saves a lead and returns precise error feedback.
 */
export const saveLead = async (lead: Lead): Promise<{ success: boolean; error?: string; sql?: string }> => {
  const client = getSupabaseClient();
  
  if (!client) {
    return { 
      success: false, 
      error: 'Client not initialized. Please configure your API key.' 
    };
  }

  try {
    const { error } = await client
      .from('leads')
      .insert([
        { 
          name: lead.name, 
          email: lead.email, 
          company: lead.company,
          role: lead.role || 'Not Specified',
          newsletter_opt_in: !!lead.newsletter_opt_in,
        },
      ]);

    if (error) {
      console.error('Lead submission failed:', error);
      
      if (error.code === '42P01') {
        return { 
          success: false, 
          error: 'The "leads" table is missing from your database.',
          sql: INITIALIZATION_SQL
        };
      }
      if (error.code === '42501') {
        return { 
          success: false, 
          error: 'Submission blocked by RLS policies. Please enable public inserts.',
          sql: 'CREATE POLICY "Allow public insert" ON leads FOR INSERT WITH CHECK (true);'
        };
      }
      return { success: false, error: `${error.message} (Code: ${error.code})` };
    }

    return { success: true };
  } catch (err: any) {
    return { success: false, error: err.message || 'A network error occurred during submission.' };
  }
};